DROP TABLE IF EXISTS TB_ACC;
CREATE TABLE TB_ACC (
  ACC_ID int(11) NOT NULL AUTO_INCREMENT,
  ACC_NAME varchar(20) NOT NULL,
  ACC_MONEY double NOT NULL DEFAULT 0,
  PRIMARY KEY (ACC_ID),
  CONSTRAINT U_TB_ACC_01 UNIQUE (ACC_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO TB_ACC (ACC_NAME, ACC_MONEY) VALUES ('zhangsan', 5000);
INSERT INTO TB_ACC (ACC_NAME, ACC_MONEY) VALUES ('wangwu', 3000);
INSERT INTO TB_ACC (ACC_NAME, ACC_MONEY) VALUES ('lisi', 10000);