CREATE DATABASE IF NOT EXISTS `TEST` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE USER 'test'@'%' IDENTIFIED BY 'password';
GRANT USAGE ON *.* TO 'test'@'%' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `TEST`.* TO 'test'@'%';
CREATE USER 'test'@'localhost' IDENTIFIED BY 'password';
GRANT USAGE ON *.* TO 'test'@'localhost' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `TEST`.* TO 'test'@'localhost';